routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use LaravelForum\Http\Controllers\UsersController;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=>true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('discussions','DiscussionsController');
Route::resource('discussions/{discussion}/replies','RepliesController');

Route::get('users/notifications',[UsersController::class,'notifications'])->name('users.notifications');
Route::post('discussions/{discussion}/replies/{reply}/mark-as-best-reply', 'DiscussionsController@reply')->name('discussions.best-reply');

app/User.php
<?php

namespace LaravelForum;

use Illuminate\Notifications\Notifiable;
use LaravelForum\Notifications\VerifyEmail;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
//has many relationship user has many discussion
    public function discussions(){
        return $this->hasMany(Discussion::class);
    }
    //has many relationship user has many replies
    public function replies(){
        return $this->hasMany(Reply::class);
    }
    public function sendEmailVerificationNotification(){
        $this->notify(new VerifyEmail());
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace LaravelForum\Http\Controllers;

use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function notifications(){
    //mark all as read

    auth()->user()->unreadNotifications->markAsRead();

    //display all notification
    return view('users.notifications',[
        'notifications'=> auth()->user()->notifications()->paginate(5)
    ]);
    }
}

resources/views/users/notifications.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
                <div class="card-header">Notifications</div>

                <div class="card-body">
                   <ul class="list-group">
                   @foreach($notifications as $notification)
                     <li class="list-group-item">
                     @if($notification->type ==='LaravelForum\Notifications\NewReplyAdded')
                     A new reply was added to your discussion-
                     <strong>{{$notification->data['discussion']['title']}}</strong>
                     <a href="{{route('discussions.show',$notification->data['discussion']['slug'])}}" class="btn btn-info btn-sm float-right">View Discussion</a>
                     @endif
                     @if($notification->type === 'LaravelForum\Notifications\ReplyMarkAsBestReply')
                     reply marked as best- <strong>{{$notification->data['discussion']['title']}}</strong> 
                     <a href="{{route('discussions.show',$notification->data['discussion']['slug'])}}" class="btn btn-info btn-sm float-right">View Discussion</a>                   
                      @endif
                     </li>
                    @endforeach
                   </ul>
                </div>
            </div>
@endsection