routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use LaravelForum\Http\Controllers\UsersController;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=>true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('discussions','DiscussionsController');
Route::resource('discussions/{discussion}/replies','RepliesController');

Route::get('users/notifications',[UsersController::class,'notifications'])->name('users.notifications');
Route::post('discussions/{discussion}/replies/{reply}/mark-as-best-reply', 'DiscussionsController@reply')->name('discussions.best-reply');

app/Discussion.php
<?php

namespace LaravelForum;

use LaravelForum\Notifications\ReplyMarkAsBestReply;


class Discussion extends Model
{
    //create a relationship
    public function author(){
        return $this->belongsTo(User::class,'user_id');
    }
   //Get Replies for a specific discussion
   public function replies(){
       return $this->hasMany(Reply::class);
   }

    //change Route model biding to use slug

    public function getRouteKeyName(){
        return 'slug';
    }
/**
 * 
 * @method Check if discussion has best reply 
 * 
 */
 public function bestReply(){
     return $this->belongsTo(Reply::class,'reply_id');
 }
 /**
  * scope method to handle filter by channel
  */

 public function scopeFilterByChannels($builder){
     if(request()->query('channel')){
        //filter
        $channel = Channel::where('slug',request()->query('channel'))->first();
        if($channel){
            return $builder->where('channel_id',$channel->id);
        }
        return $builder;
    
   }
   return $builder;
 }


    /**
     * 
     * @method decogest control 
     */
    public function markAsBestReply(Reply $reply){
        $this->update([
            'reply_id'=>$reply->id
        ]);
        if($reply->onwer->id ===$this->author->id){
            return;
        }
        $reply->onwer->notify(new ReplyMarkAsBestReply($reply->discussion));
    
    }
}

app/Http/Controllers/DiscussionsController.php
<?php

namespace LaravelForum\Http\Controllers;

use Illuminate\Http\Request;

use LaravelForum\Http\Requests\CreateDiscussionRequest;

use LaravelForum\Discussion;

use LaravelForum\Reply;


class DiscussionsController extends Controller
{


    public function __contructor(){
        $this->middleware(['auth','verified'])->only(['create','store']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('discussions.index',[
         'discussions'=>Discussion::filterByChannels()->paginate(5)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('discussions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateDiscussionRequest $request)
    {   
//add discussion and use login user relation get Id[User.php]
        auth()->user()->discussions()->create([
            'title'=>$request->title,
            'slug'=>str_slug($request->title),
            'content'=>$request->content,
            'channel_id'=>$request->channel
        ]);
        session()->flash('success','Discussion posted.');

        return redirect()->route('discussions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Discussion $discussion){
        return view('discussions.show',[
            'discussion'=>$discussion
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    /**
     * 
     * @param method to mark reply as Best
     */

     public function  reply(Discussion $discussion, Reply $reply){
    $discussion->markAsBestReply($reply);

    session()->flash('success','Marked as Best Reply');
    return redirect()->back();
     } 
}

resources/views/discussions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
<div class="card-header">Add Discussion</div>
<div class="card-body">
<form action="{{route('discussions.store')}}" method="POST">
@csrf
<div class="form-group">
<label for="title">Title</label>
<input type="text" name="title" class="form-control" value="">
</div>
<div class="form-group">
<label for="content">Content</label>
<input id="content" type="hidden" name="content">
  <trix-editor input="content"></trix-editor>
</div>
<div class="form-group">
<label for="channel">Channel</label>
<select name="channel" id="channel" class="form-control">
@foreach($channels as $channel)
<option value="{{$channel->id}}">{{$channel->name}}</option>
@endforeach
</select>
</div>
<button type="submit" class="btn btn-success">Create Discussion</button>
</div>
</form>
 </div>
@endsection
@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.0.0/trix.css">
@endsection

@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.0.0/trix.js"></script>
@endsection

resources/views/discussions/index.blade.php
@extends('layouts.app')

@section('content')
@foreach($discussions as $discussion)
<div class="card mb-2">
 @include('partials.discussion-header')
   <div class="card-body">
   <div class="text-center">
   <strong>
   {{ $discussion->title }}
   </strong>
   </div>
    </div>
            </div>
@endforeach
{{$discussions->appends(['channel' =>request()->query('channel')])->links()}}
@endsection

resources/views/discussions/show.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
@include('partials.discussion-header')
   <div class="card-body">
   <div class="text-center">
   <strong>
   {{ $discussion->title }}
   </strong>
   </div>
  <hr>
  {!! $discussion->content !!}
  @if($discussion->bestReply)
   <div class="card mt-3">
   <div class="card-header bg-success">
   Best Reply by <strong> {{$discussion->bestReply->onwer->name}} </strong>
   </div>
   <div class="card-body">
   {!! $discussion->bestReply->content !!}
   </div>
   </div>
  @endif
</div>
</div>
@foreach($discussion->replies()->paginate(3) as $reply)

<div class="card my-2">
<div class="card-header">
<div class="d-flex justify-content-between">
<div>
{{$reply->onwer->name}}
</div>
<div>
@auth
@if(auth()->user()->id === $discussion->user_id)
<form action="{{route('discussions.best-reply',['discussion'=>$discussion->slug,'reply'=>$reply->id]) }}" method="POST">
@csrf
<button type="submit" class="btn btn-outline-info btn-sm">mark as best reply</button>
</form>
@endif
@endauth
</div>
</div>
</div>
<div class="card-body">
{!! $reply->content !!}
</div>
</div>

@endforeach
{{$discussion->replies()->paginate(3)->links()}}
<div class="card my-2">
<div class="card-header">
Add a reply
</div>
<div class="card-body">
@auth
<form action="{{route('replies.store', $discussion->slug)}}" method="POST">
@csrf
 <input type="hidden" name="content" id="content">
 <trix-editor input="content"></trix-editor>
 <button class="btn btn-success btn-sm my-2" type="submit">Add Reply</button>
</form>
@else
<a href="{{route('login')}}" class="btn btn-success btn-sm">Sign In To Reply</a>
@endauth
</div>
</div>
@endsection

@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.0.0/trix.css">
@endsection

@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.0.0/trix.js"></script>
@endsection